"""empty message

Revision ID: 848e17a9cf35
Revises: 4f0717cfd7e6
Create Date: 2023-05-11 11:13:40.404464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848e17a9cf35'
down_revision = '4f0717cfd7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###