"""empty message

Revision ID: 4af5ea3c6c24
Revises: 0d997ed494b2
Create Date: 2023-05-08 15:51:13.702405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af5ea3c6c24'
down_revision = '0d997ed494b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('following_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('followed_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('followed_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('following_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###