"""empty message

Revision ID: fba2da3e1fff
Revises: c0911c8aa0fc
Create Date: 2023-05-09 16:31:14.569432

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'fba2da3e1fff'
down_revision = 'c0911c8aa0fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    if environment == "production":
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('title')
        batch_op.drop_column('post_type')

    # ### end Alembic commands ###
