"""empty message

Revision ID: a962974e6df8
Revises: 550bb143970a
Create Date: 2023-05-09 18:37:27.627780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a962974e6df8'
down_revision = '550bb143970a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('postId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('createdAt')
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('updatedAt', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DATETIME(), nullable=True))
        batch_op.alter_column('postId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###