"""empty message

Revision ID: 17379328afac
Revises: 4af5ea3c6c24
Create Date: 2023-05-08 16:41:32.830843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17379328afac'
down_revision = '4af5ea3c6c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('following_user_id', sa.INTEGER(), nullable=True),
    sa.Column('followed_user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('following_user_id', 'followed_user_id')
    )
    op.drop_table('follows')
    # ### end Alembic commands ###