"""empty message

Revision ID: 4f0717cfd7e6
Revises: ebf0dfa12dc0
Create Date: 2023-05-10 12:40:36.601639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0717cfd7e6'
down_revision = 'ebf0dfa12dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.alter_column('postId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('id')
        batch_op.drop_column('createdAt')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('post_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('post_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('updatedAt', sa.DATETIME(), nullable=True))
        batch_op.alter_column('postId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###