"""empty message

Revision ID: 58f273390084
Revises: 1fb1bf5b2c33
Create Date: 2024-05-25 06:01:13.605968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f273390084'
down_revision = '1fb1bf5b2c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_two', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_three', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_four', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_five', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_six', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_seven', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_eight', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_nine', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_ten', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('file_ten')
        batch_op.drop_column('file_nine')
        batch_op.drop_column('file_eight')
        batch_op.drop_column('file_seven')
        batch_op.drop_column('file_six')
        batch_op.drop_column('file_five')
        batch_op.drop_column('file_four')
        batch_op.drop_column('file_three')
        batch_op.drop_column('file_two')

    # ### end Alembic commands ###