"""empty message

Revision ID: 977cd66b67b0
Revises: 58f273390084
Create Date: 2024-05-25 06:30:42.624509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977cd66b67b0'
down_revision = '58f273390084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_banner', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_banner')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###